plugins {
    id 'java'
    id 'application'
}

group = 'com.swlo.filemanager'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

// Define a classe principal do aplicativo
application {
    mainClass = 'com.swlo.filemanager.FileSystemSimulator' // Substitua pelo nome correto da sua classe principal
}

test {
    useJUnitPlatform()
}

// Configuração para garantir que o encoding seja UTF-8
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    systemProperty 'file.encoding', 'UTF-8'
}

// Empacota todas as dependências no JAR
jar {
    manifest {
        attributes(
                'Main-Class': application.mainClass
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
